### ISSUE TITLE
DISKMAP command missing from VM/370 CE 1.2

### ISSUE THREAD

**Issue by luciofassio** [s390guy/vm370#119]
It is my first experience in VM being a system programmer in VSE, and i'm amazed of the richness of the environment. Wandering in the excellent help online i found that the documented DISKMAP command is missing or not recognized.

**Comment by RossPatterson** [comment]
There is a `DIRMAP EXEC` on MAINT's 191 disk that does that.

**Comment by g4ugm** [comment]
The DISKMAP is on MAINTS 535 so it should work from MAINT. Not usually needed in other IDs.

**Comment by RossPatterson** [comment]
Closing as per Dave's comment above.
