### ISSUE TITLE
The PASCAL Compiler is down-level

### ISSUE THREAD

**Issue by g4ugm** [s390guy/vm370#13]
http://bernd-oppolzer.de/job9.htm

the actual compiler which can be downloaded from the site mentioned above is version number 2021.01
(year and month of release) 
and I am working on the 2021.03 release. The compiler is still MUCH better than the 2017 version, 
it now has strings, static variables with initialization at compile time and much more, and IMO 
it now can be considered a competitor to IBMs Pascal/VS (although it still has some bugs, probably). 
In contrast to IBMs Pascal, it works on other platforms like Windows and Unix etc., too (same Pascal 
variant, no difference in the language, P-Code files can be ported between platforms). And MVS ... 
If you give it a try and find severe errors (which I don't know yet), I will try to fix them as soon as possible.

**Comment by BobBolch** [comment]
Bernd Oppolzer is working up a list of the essential files for the Stanford PASCAL compiler version 2021.01.
A PASCAL 191 disk has been added to the community edition which contains the entire set of source and runtime routines
for this release. The current PASCAL files on the VM370CE Y disk have NOT been removed or changed. The Y disk files will be replaced in a future release of the Community Edition.
