### ISSUE TITLE
DMKSNT entry for CMSTEST saved segment has wrong cylinde number

### ISSUE THREAD

**Issue by BobBolch** [s390guy/vm370#19]

**Comment by BobBolch** [comment]
Here is the correct entry:

CMSTEST  NAMESYS    SYSSIZE=256K,SYSNAME=CMSTEST,                
               VSYSADR=290,SYSVOL=VM50-1,SYSCYL=261,             
               SYSSTRT=(010,1),SYSPGCT=65,                       
               SYSPGNM=(0-15,32,3968-4015),SYSHRSG=(248,249,250),
               VSYSRES=VM50-7

**Comment by jgeorge44** [comment]
I tried the changes above and am stiull getting DASD 290 INCOMPATIBLE SYSRES trying to SAVESYS CMSTEST. I'll look into it more.
Also, could we consider changing the volser of MAINT290 from CMSDSK to CMSTST to differentiate it from MAINT190?

**Comment by BobBolch** [comment]
It did work for me after correcting the segment definition.

When I am ready to use CMSTEST, I want to make sure that any changes to the
190 are also
on the 290. I just DDR it, which would change the label back.
Bob

**Comment by BobBolch** [comment]
This fix is accepted. The CMSTEST system on the MAINT 290 disk is now a duplicate of the MAINT 190 CMS system.

**Comment by BobBolch** [comment]
Fixed in V1 R1.1
