### ISSUE TITLE
"SET CMSTYPE HT" and "SET CMSTYPE RT"

### ISSUE THREAD

**Issue by larry770** [s390guy/vm370#20]
I would like to request that the "SET CMSTYPE HT" and "SET CMSTYPE RT" commands be available for Brexx execution in future releases of VM/370 CE

Many thanks!
Larry

**Comment by BobBolch** [comment]
So what are you doing in secret while typng is off?

Accepted for next release.

**Comment by larry770** [comment]
Chuckle chuckle!
Per my post in https://groups.io/g/h390-vm, I am working on an example EXEC that so far has proven to be quite useful as and EXEC itself and as a REXX sample for the VM/370 CE. In lieu of cash, where would you like me to share the REXX code?

**Comment by BobBolch** [comment]
Hi Larry,
Just to make my checklist work, if it goes in the next release, an issue
makes sure it happens. We send REXX samples out now with our
release of BREXX and the GCC library, separate from the VM/CE release,
and intended to be more frequent. That might be the right spot.
How about posting on the h390 list so everyone can have a look, and I
will figure out what disk to distribute it on.

Thanks/Bob Bolch

**Comment by larry770** [comment]
Posted in my original post at 
https://groups.io/g/h390-vm/topic/81865561?p=Created,,,20,1,0,0::recentpostdate/sticky,,,20,2,0,81865561

**Comment by BobBolch** [comment]
Fixed in V1 R1.1
