### ISSUE TITLE
MAINT PROFILE EXEC needs reasonable additions

### ISSUE THREAD

**Issue by jgeorge44** [s390guy/vm370#21]
For building nuclei and basic edit maneuvering, please consider adding the common customizations to PROFILE EXEC on MAINT's 191 disk. Thanks!

**CP SPOOL PUN *                                                                  
CP SPOOL PRT *                                                                  
CP SET  PF12 RETRIEVE                                                           
CP SET  PF3 IMMED FILE                                                          
CP SET  PF7 IMMED UP 8                                                          
CP SET  PF8 IMMED DOWN 8**

**Comment by BobBolch** [comment]
I want to let the owner set the keys they want. I, for example, do not use any of these settings myself.
Not accepted.

**Comment by mgrossmann** [comment]
What's about copy these as an example?

I was missing PF12 a lot :)

**Comment by BobBolch** [comment]
Mike,

The intent is that you EDIT the PROFILE EXEC and
add whatever you want at the end. Each individual can have what they want.
These choices are very personal. I can tell you that PF10 should be
RETRIEVE. I used that for over 40 years, so I must be right!!!!!
(See, it's like a religion.)
Bob

**Comment by mgrossmann** [comment]
I fully understood that. 

Where I could find a summarized documentation about possible `profile exec` commands ?

**Comment by Rhialto** [comment]
The obvious solution is to set **all** PF keys to **RETRIEVE** :-)

**Comment by jgeorge44** [comment]
I think at least as a hint to potential newer users, could we add common profile customizations to the EXEC, commented out at least, so users know what the more common convenience options are available?

**Comment by jgeorge44** [comment]
> Mike, The intent is that you EDIT the PROFILE EXEC and add whatever you want at the end. 

Then we should at least document this somewhere for people who aren't familiar with VM...

**Comment by marXtevens** [comment]
VM and MVS are not user friendly, granted, and the people supporting it are making strides forward. But, the individual has to put forth some effort into learning.

> Then we should at least document this somewhere for people who aren't familiar with VM...

From ...

```
FSVIEW: PROFILE EXEC     A0                Lines 1-5/5 V80[1-79]  FSVIEW V1.2.5
&CONTROL OFF
* ACCESS MAINT TOOLS DISK
ACCESS 5E5 B/B

* Add any customizations for maint after this line.



```
to ...

```
FSVIEW: PROFILE EXEC A1                    Lines 1-9/9 V80[1-79]  FSVIEW V1.2.5
&CONTROL OFF
* ACCESS MAINT TOOLS DISK
ACCESS 5E5 B/B

* Add any customizations for maint after this line.
CP SET PF03 QUIT
CP SET PF07 BACKWARD
CP SET PF08 FORWARD
CP SET PF09 RETRIEVE
```
Wasn't much trouble, after logging in to CMSUSER

```
L CMSUSER
ENTER PASSWORD:
 
LOGON AT 01:06:41 GMT FRIDAY 11/12/21
VM Community Edition V1 R1.1
 
Y (19E) R/O
U (19D) R/O
'19D' REPLACES ' U (19D) '
U (19D) R/O
 
+-----------------------------------------------------------------------------+
|          Welcome to VM/370 and VM/380 Community Edition                     |
+-----------------------------------------------------------------------------+
 
For a list of CMS commands, type HELP CMSCMDS.  For a list of CP commands, type
HELP CPCMDS.
 
Other useful documentation and sample programs can be found on MAINT 19D,
accessed as your U disk.
 
For more details, type HELP WELCOME ( MORE
Ready; T=0.02/0.03 01:06:45
```

Where you find there is an EDIT command from HELP CMSCMDS, to then edit PROFILE EXEC A.

```
EDIT    PROFILE  EXEC     A1  V  80 ZONE=  1- 80 VERFY=  1- 80 CASE=U TRUNC= 80 
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                               
TOF:                                                                           
&CONTROL OFF NOMSG                                                              
GLOBAL TXTLIB PDPCLIB CMSLIB PLILIB FORTLIB TSOLIB                              
GLOBAL MACLIB DMSGPI CMSHRC CMSLIB OSMACRO TSOMAC                               
CP SET  PF12 RETRIEVE                                                           
CP SET  PF3 IMMED FILE                                                          
CP SET  PF7 IMMED UP 8                                                          
CP SET  PF8 IMMED DOWN 8                                                        
ACC 19D U/S                                                                     
ACC 193 E                                                                       
ACC 194 F                                                                       
ACC 195 G                                                                       
EXEC HELP WELCOME                                                               
&EXIT                                                                           
EOF:                                                                            
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                               

                                                            VM READ   VM370CE  
```

I remember being lost, with no one to help me learn VM/SP 4, other than the consultant who was installing the system for us, and I was told to leave him alone. So I bought and read manuals. 

Maybe someone wants to volunteer to set up documentation to the VM/370 Release 6 manuals on bitsavers.org, or create a minidisk with a bunch of those manuals in text format, or help with making this system friendlier for new users.

I'm not trying to be argumentative, but volunteers are few and far between, and I'm trying to do my bit by re-installing ASSIST for VM, and ZIP/UNZIP, which I/we need.

Maybe some pointers to the MECAFF tools, such as EE, FSVIEW, and XLIST?

 ... Mark S.

**Comment by marXtevens** [comment]
Having shot my mouth off above, maybe we could add:

`CP SET PF01 IMMED HELP`

To PROFILE EXEC for CMSUSER, and MAINT?

 ... Mark S.

**Comment by BobBolch** [comment]
http://www.bitsavers.org/pdf/ibm/370/VM_370/Release_6/GC20-1819-2_IBM_Virtual_Machine_Facility_370_CMS_Users_Guide_Rel_6_PLC_17_Apr81.pdf

The CMS Users Guide is recommended reading for those who want to use VM/370. It contains an overview of the common CP and CMS commands and many examples. Almost any CMS command can be used in a PROFILE EXEC.
