### ISSUE TITLE
OSBASIC and FORTRAN 191 disks misnamed

### ISSUE THREAD

**Issue by jgeorge44** [s390guy/vm370#22]
OSBASIC's 191 disk as been labeled "TST" for as long as I can remember there being a sixpack around. It seems to build and work properly, so there's no need (I think) for it to remain labeled as a test volume, that user should own the minidisk as OSB191 for more traditional naming.

FORTRAN's 191 disk is also named TST as well.

I don't know how to make this like a "walk your dog first" priority, it's not a big deal, but still worth the quick change maybe?

**Comment by BobBolch** [comment]
Accepted

**Comment by BobBolch** [comment]
Fixed in V1 R1.1
