### ISSUE TITLE
MAINT 494 disk damaged

### ISSUE THREAD

**Issue by jgeorge44** [s390guy/vm370#23]
The MAINT 494 minidisk seems to be damaged. It mounts okay and you can list files on it, but copying anything off of the minidisk results in a DMSCPY error on (presumably) any file accessed: 

ACC 494 A
DEFINE T3350 as 100 cyl 15
FORMAT 100 Z
(YES, TMP100)

copy * * a = = z (oldd 
DMSCPY901T UNEXPECTED ERROR AT 021A4A: PLIST 'RDBUF ASMIF EXEC A1' AT 023494, BASE: 020000, RC 3.
Ready(00256); T=0.01/0.01 18:27:08
 
copy * text a = = z
DMSCPY901T UNEXPECTED ERROR AT 021A4A: PLIST 'RDBUF DMKACO TEXT A1' AT 023494, BASE: 020000, RC 3.
Ready(00256); T=0.01/0.02 18:28:16
 
copy * macro a = = z
DMSCPY901T UNEXPECTED ERROR AT 021A4A: PLIST 'RDBUF LDRST MACRO A1' AT 023494, BASE: 020000, RC 3.

copy DMSLDR   AUXR60   A1 = = z
DMSCPY901T UNEXPECTED ERROR AT 021A4A: PLIST 'RDBUF DMSLDR AUXR60 A1' AT 023494, BASE: 020000, RC 3.

(it's also mislabeled, but since the disk is mostly useless at this point, thats not worth complaining about :) )

**Comment by BobBolch** [comment]
This disk is passed along from the Sixpack 1.3 release and the earlier 1.3 beta 3 level.
I expect we will discard this minidisk.

**Comment by BobBolch** [comment]
MAINT 092 and MAINT 494 are unused and will be deleted.

**Comment by BobBolch** [comment]
Fixed in V1 R1.1
