### ISSUE TITLE
Running DOSVS in the Community Edition

### ISSUE THREAD

**Issue by BobBolch** [s390guy/vm370#25]
DOS/VS VIRTUAL MACHINE INITIAL SET UP
*************************************

1) Download the DASDs of George Shedlock's 5-pack:
   http://dosvs.31bits.net/DOSVS_5Pack_V1.0-full.zip
   Unzip the file and put the emulated DASDs in the "disks" folder of VM/370 CE

2) Update vm370ce.conf for those DASDs:

   09A0   3350   disks/DOSR34.3350.CCKD
   09A1   3350   disks/PWRR34.3350.CCKD
   09A2   3350   disks/WORK01.3350.CCKD
   09A3   3350   disks/VSAM01.3350.CCKD
   09A4   3350   disks/OPTLB1.3350.cckd

   (use the indicated addresses and the lower case for OPTLIB1).

3) IPL VM/370 CE normally;

4) Logon to MAINT and edit USER DIRECT A to change the DOSVS directory entry:

   a) remove the VIRT=REAL option
   b) replace IPL 190 by IPL CMS
   c) add  the line:

      LINK MAINT 19D 19D RR

   Save the file, and update the directory:
   direct user

   Then, logoff of MAINT;

5) Logon to DOSVS and create two files:
   a) NOTHING JCL A, containing

      // JOB NOTHING
      /&

      (This nothing job will be run at IPL and will ready the card reader of DOS/VS)

   b) DOSIPL EXEC A, containing
      CP SPOOL PUNCH *
      PUNCH NOTHING JCL A ( NOH
      CP SPOOL PUNCH OFF
      IPL 360

      (The exec will put the nothing in the virtual card reader before the IPL)

The virtual machine is now ready for the IPL of DOS/VS.

IPL OF DOS/VS R34
*****************
1) Logon to DOSVS and, at the Ready prompt, run the DOSIPL EXEC. Type
   dosipl
   followed by ENTER *once*. Don't do anything on this (logon) console anymore.
   Be sure that it is in RUNNING state.
2) Open a new 3270 connection, press the CLEAR key and dial DOSVS at the address 01F:
   dial dosvs 01f (followed by ENTER)
   You should get the message:
   DIAL DOSVS 01F
   DIALED TO DOSVS      01F
   Press ENTER an other time. You should get the message:

   0I04I IPLDEV=X'360',VOLSER=DOSR34,CPUID=...
   0I03A SPECIFY SUPERVISOR NAME

   *This 3270 is now the operating console of DOS/VS.*

   To answer message 0I03A, type:

   $$a$sup1 (and press ENTER *twice*). When you get the message:

   0I10A GIVE IPL CONTROL COMMANDS
   then type the sequence of commands below (in lower case), each one followed by ENTER :
   set
   
   0I71I READ DEVICE TYPE FOR SYSLOG INSERTED IN SYSLOG PUB
   dpd

   BG 1T00A  WARM START COPY OF SVA FOUND
   keep

   BG 1I00A  READY FOR COMMUNICATIONS
   stop
   batch f1

   0D07D  ENTER RESPONSE
   F1
   assgn sysin,sysres
   F1 1T20I  SYSIN  HAS BEEN ASSIGNED TO X'360
   press the ENTER key
   (many messages displayed)

   0D07D  ENTER RESPONSE
   BG   
   assgn sysin,reader
   
   0D07D  ENTER RESPONSE
   F2   
   assgn sysin,reader   
   0D07D  ENTER RESPONSE
   F4   
   assgn sysin,reader   
   0D07D  ENTER RESPONSE
   F3   
   assgn sysin,reader

   0D07D  ENTER RESPONSE
   F2

   assgn sysin,reader

   BG 1T20I  SYSIN  HAS BEEN ASSIGNED TO X'00C'
   0D07D  ENTER RESPONSE
   BG

   Press ENTER and do the same for F2, F4 and F3

   Once you have the messages:
   
   F1 1Q34I   BG WAITING FOR WORK
   F1 1Q34I   F2 WAITING FOR WORK
   F1 1Q34I   F4 WAITING FOR WORK
   F1 1Q34I   F3 WAITING FOR WORK

   and the messages regarding the NOTHING job, enter the command:

   r rdr,*xx
   l lst,all

The IPL of DOS/VS is complete and the system is ready for work.

SHUTDOW OF DOS/VS R34
*********************
7) To shutdown the system, type the commands, at the DOS/VS console:
   pend

   0D07D  ENTER RESPONSE
   F1

   /&

   0D07D  ENTER RESPONSE
   F2

   unbatch

   0D07D  ENTER RESPONSE
   F4

   unbatch

   0D07D  ENTER RESPONSE
   F3

   unbatch

   0D07D  ENTER RESPONSE
   BG

   rod

   0D07D  ENTER RESPONSE
   F1

   unbatch

   0D07D  ENTER RESPONSE
   BG

   stop

Then, at the DOSV/VS login console, type:

#CP logoff

This will drop the dialed console and logoff the DOS/VS virtual machine.

**Comment by jgeorge44** [comment]
Bob,

Could DOSIPL EXEC A be run as PROFILE EXEC A so that this would happen automatically at logon? (with messaging to the user that DOS/VS is IPLing and the terminal should be left alone?)

Or would making it the login profile allow AUTOLOG DOSVS and then not worry about a connected terminal at all?

**Comment by BobBolch** [comment]
Both of these ideas can be done. I would suggest that it not be shipped that way, so that any errors in the initial setup could be easily detected. What if we add those steps as optional at the end of the instructions?

**Comment by jgeorge44** [comment]
Admittedly errors in PROFILE EXEC are tricky for some because ACCESS (NOPROF isn't as common as it probably should be. I guess even leaving it as DOSIPL EXEC would work and we could just document that AUTOLOG DOSVS DOSVS DOSIPL to launch it would do the trick as well.

**Comment by BobBolch** [comment]
Read the dosvs.txt file in the Community Edition distribution directory for the latest version of the instructions.

**Comment by BobBolch** [comment]
Fixed in V1 R1.1
