### ISSUE TITLE
Re-address VMCE DASD (split from issue #12)

### ISSUE THREAD

**Issue by jgeorge44** [s390guy/vm370#31]
@BobBolch opined:

I had planned to consolidate the Community Edition 3350s on a single string
of addresses from 140-14F.
I see that the tk4- setup uses those addresses. It is easy to change the
tk4- setup? Could we wall off
a set of addresses (with some spares) to be used for a tk4- guest? Maybe I
should use
something else for VM disks (6A0-6BF?).

Bob

_Originally posted by @BobBolch in https://github.com/s390guy/vm370/issues/12#issuecomment-822781992_

**Comment by BobBolch** [comment]
To simplify the use of an MVS guest, the VM system 3350 disks will be relocated to
addresses 6A0-6BF.

These changes redefine the DMKRIO disk definitions for volumes to be used by an MVS TK4- system:

match dmkrio assemble f = = a                              
COMPARING 'DMKRIO ASSEMBLE F1' WITH 'DMKRIO ASSEMBLE A1'.  
REPLACING 1 RECORD(S) STARTING AT RECORD NUMBER 36 ...     
*        RDEVICE ADDRESS=(170,16),DEVTYPE=3375,CLASS=DASD  
REPLACING WITH 3 RECORD(S) ...                             
         RDEVICE ADDRESS=(170,16),DEVTYPE=3375,CLASS=DASD  
         RDEVICE ADDRESS=(180,16),DEVTYPE=3380             
         RDEVICE ADDRESS=(190,16),DEVTYPE=3390,CLASS=DASD  
REPLACING 1 RECORD(S) STARTING AT RECORD NUMBER 56 ...     
*        RDEVICE ADDRESS=(270,16),DEVTYPE=3375,CLASS=DASD  
REPLACING WITH 1 RECORD(S) ...                             
         RDEVICE ADDRESS=(270,16),DEVTYPE=3375,CLASS=DASD  
REPLACING 1 RECORD(S) STARTING AT RECORD NUMBER 58 ...     
*        RDEVICE ADDRESS=(290,16),DEVTYPE=3390,CLASS=DASD  
REPLACING WITH 1 RECORD(S) ...                             
         RDEVICE ADDRESS=(290,16),DEVTYPE=3390,CLASS=DASD  
INSERTING 2 RECORD(S) AFTER RECORD NUMBER 210 ...          
         RCTLUNIT ADDRESS=180,CUTYPE=3830,FEATURE=16-DEVICE
         RCTLUNIT ADDRESS=190,CUTYPE=3830,FEATURE=16-DEVICE
Ready; T=0.01/0.03 10:07:29                                

The MVS 3375 and 3390 disks are defined to CP as unsupported devices. This 
definition prevents CP from attempting to use thses devices in any way, other than to
pass through I/O requests from the MVS guest. Assembling DMKRIO with these changes
produces an expected RC=4. Here is the section from GC20-1801-10:

In addition, any other device that can be attached to a real
System/370 can be specified in the RDEVICE macro by its device
type. For unsupported devices that do not have a device type
listed under the DEVTYPE operand, you should code the subclass on
the CLASS operand. Then unsupported devices can be dedicated to a
virtual machine, and CP can log the error recordings, if there are
any. CP does not use unsupported devices for its own operations.
If a device specified in the RDEVICE macro is not supported by
VM/370, the following MNOTE message (warning level) is generated:
UNSUPPORTED DEVICE TYPE
The device is generated as an unsupported device. An unsupported
device can only be used if it is dedicated to a virtual machine. It
is dedicated to a virtual machine if a DEDICATE control statement
is coded in the VM/370 directory for the virtual machine, or if it
is attached to it by the CP ATTACH command.

**Comment by BobBolch** [comment]
Fixed in V1 R1.1
