### ISSUE TITLE
Help has wrong version

### ISSUE THREAD

**Issue by GaryDinoNut** [s390guy/vm370#34]
HELP for CPCMDS and CMSCMDS both display 'VM/370 Release 6 "Sixpack" '.

**Comment by RossPatterson** [comment]
`HELP CPCMDS` in VM/CE 1.2 says in the first line:

`VM/370 Release 6 Community Edition CP Commands`

`HELP CMSCMDS` says:

`VM/370 Community Edition CMS Commands and Help Topics`

We should change `CPCMDS HELP$CP` to match `CMSCMDS HELP$CM`.  Or maybe, instead, rely on the automated menu created by `HELP CP MENU` and `HELP CMS MENU` and delete both of these files.
