### ISSUE TITLE
REXXTEST EXEC has ADDRESS SYSTEM instead of ADDRESS COMMAND

### ISSUE THREAD

**Issue by rvjansen** [s390guy/vm370#5]
REXXTEST EXEC has ADDRESS SYSTEM instead of ADDRESS COMMAND. This was changed in bREXX to correspond to VM/CMS usage. This makes the "CP QUERY TIME" call fail.

**Comment by BobBolch** [comment]
The copy of REXXTEST EXEC on the CMSUSER 191 disk was a backlevel copy. The REXXTEST EXEC on the Y-disk is correct. We will remove the erroneous copy.
