### ISSUE TITLE
Update various help files

### ISSUE THREAD

**Issue by BobBolch** [s390guy/vm370#59]
Update help files from the community. Files are located in:

https://groups.io/g/h390-vm/files/Help%20File%20Updates

**Comment by marXtevens** [comment]
I have downloaded the above files, edited them for consistency. and posted the originals and the updates in the following GitHub repository. The files are in ASCII.

https://github.com/marXtevens/VM_370_HELP

**Comment by BobBolch** [comment]
I wanted to load the original help files, then the changed versions so we
could use GITHUB releases to see the changed lines. We would create a new
help file release for each release. Is that possible?

Should we put these in the same github repository where the issues are?

**Comment by marXtevens** [comment]
I'm not very conversant with GitHub, yet, but I do have original and updated versions in the repository.

The following link shows the original and the updated versions of BASIC HELPCMD.
https://github.com/marXtevens/VM_370_HELP/commits/master/BASIC.HELPCMD.D1

The original BASIC HELPCMD can be seen here.
https://github.com/marXtevens/VM_370_HELP/blob/5d93f173af959a467e2126273a77933531834a80/BASIC.HELPCMD.D1

The updated file is here.
https://github.com/marXtevens/VM_370_HELP/blob/master/BASIC.HELPCMD.D1

The changes can be seen here.
https://github.com/marXtevens/VM_370_HELP/commit/0ddd83ea370992d13025257f64f8059622e8c0c5#diff-474e44f2c923607e8e3669c732fd016a6ca5ae4c96d978cb14b4ae83780b8a6d

I put them where I did, so we at least had them on GitHub. Feel free to copy, fork, whatever to wherever. Or tell me where you want them, and I can try to get them there.

I am here to help.

 ... Mark S.

**Comment by marXtevens** [comment]
Concerning releases, I can identify what I have uploaded as a particular release, or even as a pre-release. I would assume that by migrating it to another repository, the same would be true there.

We can also create tags, and use them, but I don't have suggestions as to what to use at the moment.

 ... Mark S.

**Comment by BobBolch** [comment]
I confess that I am not very familiar with githib either.
I think moving the information you collected into the same
place where the issues are makes things easier. If you
are authorized, would you please place the help work
in progress to S390guy/vm370. If you are not authorized, I will
find out how to authorize you for full access.
Thanks/B

**Comment by s390guy** [comment]
I think you can request membership in s390guy/vm370 and github will
notify me.   I am the owner of this repo from github's perspective.
Harold Grovesteen

**Comment by BobBolch** [comment]
Thanks, Harold. If you can authorize Mark, that would be great. (I didn't see any way for me to do it.)

**Comment by s390guy** [comment]
Just to be clear.  Mark, you will need to create a userid on
github.com.  Request joining the group (with that user ID) and I can go
from there.
Harold

**Comment by marXtevens** [comment]
I can not request to join. I must be invited.

Instructions are found at:

https://docs.github.com/en/account-and-profile

Look for "Inviting collaborators to a personal repository"

My username on github is: marXtevens

 ... Mark S.

**Comment by s390guy** [comment]
Mark, I believe github should be sending you an invitation to join.  At least that is what it is claiming to me.

**Comment by marXtevens** [comment]
Harold,

I received the e-mail, and I have joined the repository. I am now reading up on how to merge the two, without losing history.

Thank you for your time.

 ... Mark S.

**Comment by s390guy** [comment]
As a collaborator you should be able to both pull from the repo and commit changes to it, among a large number of other activities.  Collaborator has a lot of power within the repo.  I would also strongly recommend installing a graphical tool for these activities.  I gave up a long time ago use of command line git.  There are graphical git tools for both Windows and Linux.

I use SmartGit.  It is a Java app so runs on either Windows or Linux.  Fish (the SDL Hyperion manager) uses a Windows specific tool.  I do not remember its name.  Just ask on the main Hercules email list.  I am sure Fish will be happy to share.

Harold

**Comment by s390guy** [comment]
I am going to go further.   If you are new to git, definitely use a git tool that understand github.  Do not try command line git here.  That goes for all collaborators.

Learn command line git on some other repo.

Harold

**Comment by BobBolch** [comment]
Please stop using this issue to talk about logicistics and github process.
That discussion has nothing to do with HELP files.

**Comment by marXtevens** [comment]
See the following link to compare original files with updates.

https://github.com/s390guy/vm370/pull/70/commits/526f05cdb0c1d52eaf5fca73d6b4b55fb21f2dc4
