### ISSUE TITLE
Update HELP command to use full screen by default

### ISSUE THREAD

**Issue by BobBolch** [s390guy/vm370#60]
Use logic similar to this in the HELP command:

&CONTROL OFF NOMSG                    

STATE FSQERY MODULE *                 

&IF &RETCODE NE 0 &GOTO -LM           

                                       

FSQRY STATE                           

&IF &RETCODE NE 0 &GOTO -LM           

FSHELP &1 &2 &3 &4 &5 &6 &7 &8        

&EXIT                                 

 

-LM

**Comment by marXtevens** [comment]
What kind of help are you looking for? Someone to modify/write code? Which EXECs need writing/enhancing?

 ... Mark S.

**Comment by BobBolch** [comment]
Dave proposed that we have the HELP command operate in full screen mode and
supplied an update to the HELP EXEC that calls a program called FSHELP when
the caller is on a 3270. His mod branches to the old code if the caller is
using a line mode logon session.

The problem is that the documented HELP command syntax is different and not
compatible with the syntax from the FSHELP command. We need rework this to
present one documented syntax for the HELP command, and use the same
command arguments to produce the same content for fullscreen and linemode.

The first step is to design and propose the new HELP command syntax.

**Comment by marXtevens** [comment]
Proposed HELP EXEC  Syntax & Documentation.

```
HELP                                                           CMS EXEC command

Use the HELP command to display helpful information about CMS and CP commands.
The format of the HELP command is:
+----------+------------------------------------------------------------------+
| HELP     | [ command ] [ topic ] [ ( BRIEF|ALL|MORE|REBUILD [ ) ]]          |
+----------+------------------------------------------------------------------+
where:

command  is the CMS or CP command for which help is to be displayed. If no
         command is entered a full screen menu of available help commands is
         displayed.

topic    is the operand, subcommand, statement, or other topic to be displayed
         for the command.  'topic' can be an operand of the CMS or CP QUERY
         or SET command, a DEBUG or EDIT subcommand, or an EXEC statement or
         topic.

Options:

BRIEF    specifies that only a summary of the topic, including syntax, is to be
         displayed.  BRIEF is the default. This option is no longer processed,
         as all help information is displayed.

ALL      specifies that all of the help information for the topic is to be
         displayed. This option is no longer processed, as all help information
         is displayed.

MORE     specifies that additional information for the topic is to be
         displayed.  This is typically usage notes and command responses. This
         option is no longer processed, as all help information is displayed.

REBUILD  When invoked without a topic, HELP looks for a file MENU FSHELP on 
         all accessed disks and displays this file as top level menu. If this
         file is not found, the help menu is built based on the help files on
         all accessed disks (with filetype HELPxxx, see above), grouping the
         topics by the command types CMS, CP, EE, EDIT, DEBUG, EXEC. This help
         file is automatically saved in the file MENU FSHELP A2. If necessary
         (for example to include new help topics), this menu help file can be
         regenerated on disk A by invoking HELP with only the option REBUILD.

For a list of CMS commands, type HELP CMSCMDS.  For a list of CP commands, type
HELP CPCMDS.

Usage Notes:

PF-Keys
-------

Browsing through the help information, navigating to other topics and leaving
HELP is typically controlled with the PF-keys. The commands assigned to PF
keys can be customized in the EE profiles, FSHELP has the following default
assignments  (summarized the screen bottom line):

  PF01  : GOTO
  PF02  : GOTO
  PF03  : BACK
  PF04  : /
  PF05  : TOP
  PF06  : PGUP
  PF07  : PGUP SHORT
  PF08  : PGDOWN SHORT
  PF09  : PGDOWN
  PF10  : BOTTOM
  PF12  : GOTO
  PF15  : QUIT
  PF16  : -/

Commands
--------

The following commands are supported on the subcommand program prompt of
HELP:

+----------+------------------------------------------------------------------+
| Help     | topic                                                            |
+----------+------------------------------------------------------------------+

Navigate to the specified help topic, pushing the current topic onto the stack.

+----------+------------------------------------------------------------------+
| GOto     |                                                                  |
+----------+------------------------------------------------------------------+

Navigate to the topic identified by the word where the cursor is in the help
text (the cursor must be in the help text area).
If no such topic exists, an error message is displayed and the cursor stays at
the current place in the help text.

+----------+------------------------------------------------------------------+
| Back     |                                                                  |
+----------+------------------------------------------------------------------+


Close the current topic and display its predecessor in the help topic stack.
If the initial topic is currently displayed, HELP is terminated.

+----------+------------------------------------------------------------------+
| TOp      |                                                                  |
+----------+------------------------------------------------------------------+

Scroll to the top of the help topic.

+----------+------------------------------------------------------------------+
| PGUP     | [ SHORT ]                                                        |
+----------+------------------------------------------------------------------+

Scroll up the topic by one page height. If the option SHORT is given,
scrolling is done only by 2/3 page height.

+----------+------------------------------------------------------------------+
| PGDOwn   | [ SHORT ]                                                        |
+----------+------------------------------------------------------------------+

Scroll down the topic by one page height. If the option SHORT is given,
scrolling is done only by 2/3 page height.

+----------+------------------------------------------------------------------+
| BOTtom   |                                                                  |
+----------+------------------------------------------------------------------+

Scroll to the bottom of the help topic.

+----------+------------------------------------------------------------------+
| Quit     |                                                                  |
+----------+------------------------------------------------------------------+

Terminate HELP.

+----------+------------------------------------------------------------------+
|          | /text/                                                           |
+----------+------------------------------------------------------------------+

Search forward for text in the current help page.

+----------+------------------------------------------------------------------+
|          | -/text/                                                          |
+----------+------------------------------------------------------------------+

Search backward for text in the current help page.

+----------+------------------------------------------------------------------+
|          | /                                                                |
+----------+------------------------------------------------------------------+

Repeat the last search in the search direction last used.

+----------+------------------------------------------------------------------+
|          | -/                                                               |
+----------+------------------------------------------------------------------+

Reverse the search direction and repeat the last search in the new search
direction.


Customizing HELP
------------------

HELP can be customized with the following commands in the EE profiles
(PROFILE EE or SYSPROF EE). Please note: FSHELP is used rather than HELP in
the following customizations.

+----------+------------------------------------------------------------------+
| PF       | FSHELP  pfno  command  [ parameters ... ]                        |
|          | FSHELP  CLEAR pfno                                               |
+----------+------------------------------------------------------------------+

Set or clear the command issued by a PF key. The pfno must be a number from
1 to 24, the maximal command length is 120 characters.

+-----------+-----------------------------------------------------------------+
| INFOLines | FSHELP  CLEAR                                                   |
|           | FSHELP  ADD infoline-text                                       |
+-----------+-----------------------------------------------------------------+

Control the information line at the bottom of the screens, usually describing
the PF key settings. HELP supports only one configurable information line.
CLEAR will display an empty line, ADD will display the text passed.
```

**Comment by marXtevens** [comment]
Reading the original HELP HELPCMD, I get the impression the following should work. Is my understanding faulty?

```
help cpset emsg
CPSET is not a valid topic for EMSG
Ready(00024); T=0.01/0.01 21:07:09
help cmsset abend
CMSSET is not a valid topic for ABEND
Ready(00024); T=0.01/0.01 21:07:22
```

 ... Mark S.

**Comment by BobBolch** [comment]
The HELP data file types on the MAINT 19D disk have these file types:
HELPCMD  HELPCMD2
HELPDBG HELPDBG2
HELPEDT HELPEDT2
HELPEE
HELPEXC HELPEXC2

That means that only these forms work:
HELP command
HELP DEBUG subcommand
HELP EDIT subcommand
HELP EXEC subcommand

There are no help files to support HELP CPSET XXX or HELP CMSSET XXX.
However the 4 HELP commands I listed do not work with FSHELP.
The goal is to have a syntax that both linemode help and fullscreen help
support.
That means modifying HELP EXEC, FSHELP MODULE, or both.
Does what I am saying make sense?
/B

**Comment by marXtevens** [comment]
What you are saying is making sense.. I cobbled a help file, to document the new & improved help command, above. If that works, with, or without changes, then we can work on altering the HELP EXEC.

Testing the what you stated above, I was able to get help using:

```
HELP EDIT AUTOSAVE
and
HELP EDIT AUTOSAVE (ALL
```

Because the following files exist:

```
l autosave help* * (date
Filename Filetype Fm  Format    Recs Blocks     Date    Time
AUTOSAVE HELPEDT  U2  V    79     16      2  06/07/10    9:55
AUTOSAVE HELPEDT2 U2  F    80     21      3  06/09/09   18:13
Ready; T=0.01/0.01 13:25:04
```

So now I understand that. Thank you!  We would need to define and create files along the lines of the following, for what I was trying, to work. 

```
ABEND HELPCMSS
or
EMSG HELPCPSS
```

Type the following:

`FSHELP DEBUG`

Then move the cursor to BREAK, or any of those commands in that column, and press PF1. It will display that subcommand.

Typing:

`FSHELP DEBUG BREAK`

Just shows the DEBUG, which puts you at the same place as above.

Now, is this broken, or just different? Typing:

```
FSHELP BREAK DEBUG
or
FSHELP BREAK
```
Does show help for the BREAK subcommand for DEBUG. I'll try to test having a fake BREAK subcommand for a topic, and see what happens, when there are two identical subcommands.

Lastly, you need to invite me, to be a collaborator.  Instructions are found at:

`https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository`

My username on github is: marXtevens

I Hope This Helps

 ... Mark S.

**Comment by BobBolch** [comment]
You don't have to make up anything to get duplicate subcommands. 
See CHANGE, DEFINE, DUMP, EDIT, HX, PUNCH, SET, STORE, and TYPE.
Linemode HELP uses a syntax that names both the command and subcommand names.
Fullscreen FSHELP currently cannot resolve these duplicates. 

"broken or just different" - It's just different, but to merge HELP and FSHELP into one command, they cannot be different!

In order to merge the HELP and FSHELP commands, do you see that one has to change? 
Whatever operands are present, a given set of operands must display the same help file as a result for either linemode or fullscreen. Only then can we merge them into one command.

**Comment by marXtevens** [comment]
> In order to merge the HELP and FSHELP commands, do you see that one has to change?
> Whatever operands are present, a given set of operands must display the same help file as a result for either linemode or fullscreen. Only then can we merge them into one command.

I had to leave this and sit and think for a while. Are you saying that if I enter:

HELP access ( more
or:
FSHELP access ( more

They would display the same text? The only difference being "... MORE" for HELP, and full screen for FSHELP?

 ... Mark S.

**Comment by marXtevens** [comment]
> In order to merge the HELP and FSHELP commands, do you see that one has to change?
> Whatever operands are present, a given set of operands must display the same help file as a result for either linemode or fullscreen. Only then can we merge them into one command.

I had to leave this and sit and think for a while. Are you saying that if I enter:

HELP access ( more
or:
FSHELP access ( more

They would display the same text? The only difference being "... MORE" for HELP, and full screen for FSHELP?

 ... Mark S.

**Comment by g4ugm** [comment]
Mark,

The issues are not with simple commands like that they work. Its when you get into the way sub commands you get differences.

So 

 

HELP EXEC ARGS

 

Returns help on the EXEC ARGS statement whereas 

 

FSHELP EXEC ARGS

 

Just returns help on EXEC. I think it hasn’t caught up with some changes to help…

 

Dave

**Comment by BobBolch** [comment]
Mark and Dave,
I am going to look over the FSHELP code to see if it can be made to do what
I want.
Let's put this on pause for a few days.
Bob
