### ISSUE TITLE
No Hercules log file is written on windows.

### ISSUE THREAD

**Issue by g4ugm** [s390guy/vm370#62]
After running Hercules a "log.txt" file is created but it is empty. The reason is that in the start batch file line 3 contains

start hercules -f vm370ce.conf > Log.txt

sadly the effect of the "> Log.txt" is to redirect the output of the "start" command, not the "hercules" command.

It appears that this command needs to be:-

start cmd /c hercules -f vm370ce.conf ^> Log.txt

which is nasty as it starts a new instance of the CMD processor.

**Comment by Fish-Git** [comment]
_**FYI:**_ &nbsp;For the very reason you describe, Hercules v4.4 was enhanced to now accept several new options (`-o logfile` or `-output=logfile` or `--logfile=logfile`) allowing you to specify the path of the log file _without_ having to use redirection syntax.

* https://sdl-hercules-390.github.io/html/hercinst.html#arguments

E.g:

     start hercules -f vm370ce.conf -o Log.txt

This of course doesn't help those who still insist on running v3.x.
