### ISSUE TITLE
Add BLOCKTAP MODULE specific to VM/370

### ISSUE THREAD

**Issue by BobBolch** [s390guy/vm370#63]
This makes it possible to load some of the older VMSHARE and Waterloo tapes that were blocked at a 64K block size, to save tape space.
The BLOCKTAP version needed is built by removing the changes for VM/SP and later systems.

**Comment by marXtevens** [comment]
For what it is worth, I have been successfully using the following version from and for the VM Workshop and UW tapes. 
http://www.smrcc.org.uk/members/g4ugm/shedlock/90PCWT.AWS.ZIP

> l blocktap * * ( date
> Filename Filetype Fm  Format    Recs Blocks     Date    Time
> BLOCKTAP ASSEMBLE T1  F    80   1433    144  05/29/90   18:14
> BLOCKTAP AUXBLK   T1  F    80      4      1  05/29/90   18:16
> BLOCKTAP BCMODE   T1  F    80     52      6  05/29/90   18:15
> BLOCKTAP CANCER   T1  F    80      1      1  05/29/90   18:17
> BLOCKTAP CNTRL    T1  F    80      2      1  05/29/90   18:30
> BLOCKTAP EOT      T1  F    80      3      1  05/29/90   18:17
> BLOCKTAP MEMO     T1  F    80     84      9  05/29/90   18:15
> BLOCKTAP MODULE   T1  V  5448      3     11  05/29/90   18:41
> BLOCKTAP SILENCE  T1  F    80     72      8  05/29/90   18:17
> BLOCKTAP TEXT     T1  F    80    119     12  05/29/90   18:31
> Ready; T=0.01/0.01 20:01:51

I Hope This Helps

**Comment by BobBolch** [comment]
This is the list I used to populate the distribution disk for the next release. 
A HELP file is still needed.

**Comment by marXtevens** [comment]
What filetype name? One file, or a main, and ( MORE ?
Thanks!

**Comment by BobBolch** [comment]
Mark, If you could make the BLOCKTAP MEMO into  a BLOCKTAP HELPCMD and BLOCKTAP HELPCMD2 for the HELP (MORE file that would be a big help! Just look at a few samples of these two filetypes on the 19D U disk, to see the contents each file usually has.

**Comment by marXtevens** [comment]
```
Ready; T=0.09/0.18 17:14:37
TAPE 181 ATTACHED
vmfplc2 rewind
INVALID FUNCTION 'REWIND'.
Ready(00024); T=0.01/0.01 17:15:27
vmfplc2 rew
Ready; T=0.01/0.01 17:15:34
vmfplc2 dump blocktap * a
 DUMPING.....
 BLOCKTAP HELPCMD  A1
 BLOCKTAP SCRIPT   A1
Ready; T=0.01/0.01 17:15:47
vmfplc2 wtm 2
Ready; T=0.01/0.01 17:15:58
vmfplc2 rew
Ready; T=0.01/0.01 17:16:08
vmfplc2 scan ( eot
 SCANNING....
 BLOCKTAP HELPCMD  A1
 BLOCKTAP SCRIPT   A1
 END-OF-FILE OR END-OF-TAPE
 END-OF-FILE OR END-OF-TAPE
Ready; T=0.01/0.01 17:16:14
```
[2022-01-05.BLOCKTAP.HELP.het.zip](https://github.com/s390guy/vm370/files/7818348/2022-01-05.BLOCKTAP.HELP.het.zip)

Please let me know of any changes you think are necessary.

 ... Mark S.

**Comment by BobBolch** [comment]
BLOCKTAP code and HELP files are staged for distribution in the next VM370CE release.
