### ISSUE TITLE
PER command traps not working with ECPSVM YES

### ISSUE THREAD

**Issue by BobBolch** [s390guy/vm370#66]
Basic PER traps are not working with ECPSVM ON in the Hercules configuration file.

**Comment by BobBolch** [comment]
Bob Polmanter figured out that a fix to DMKDSP was accidently omitted from the AUXHRC file in later versions of the VM Sixpack, and in all versions of the VM Community Edition. The fix is to correct the DMKDSP AUXHRC file to include update file DMKDSP HRC074DK. 

The update is staged for the next Community Edition release.

**Comment by RossPatterson** [comment]
HRC074DK was incomplete.  See https://github.com/SDL-Hercules-390/hyperion/issues/465 for details.  The additional fix was trivial.

[DMKDSP.AUXLCL.TXT](https://github.com/user-attachments/files/15687750/DMKDSP.AUXLCL.TXT)
[DMKDSP.RAP007DK.TXT](https://github.com/user-attachments/files/15687751/DMKDSP.RAP007DK.TXT)

**Comment by RossPatterson** [comment]
Fix has been uploaded to https://groups.io/g/h390-vm/files/hrc080dk.vmarc as HRC080DK.
