### ISSUE TITLE
Linux script may kill X3270 sessions it did not start

### ISSUE THREAD

**Issue by g4ugm** [s390guy/vm370#8]
he script "vm370ce.sh" fires two x3270 instances and, at the end, there is pipe sequence to kill all the x3270 instances, even they are not related to the execution of the system. There is a command line parameter (-once) that does just that:

 -once  Causes  x3270 to exit after a host disconnects.  This option has
        effect only if a hostname is specified on the command line.

  The loopback address works as a hostname.  I tested the change and it worked well.

**Comment by BobBolch** [comment]
This change is accepted.
Bob

**Comment by BobBolch** [comment]
Thanks to Fernando M. Roxo da Motta for reporting this issue and supplying a correction.

**Comment by BobBolch** [comment]
Fixed in V1 R1.1
