### ISSUE TITLE
Floating Point Errors with SDL Hercules 4.3.0.10296-

### ISSUE THREAD

**Issue by g4ugm** [s390guy/vm370#9]
There is a bug in the above Hercules which affects Floating Point and causes the SNTPARS EXEC to fail

. Disable ECPS disp1 and disp2 e.g.

ecpsvm disable disp2 disp2

a fix is available but currently requires you to build Hercules.

**Comment by BobBolch** [comment]
For Hyperion users, if you use a Hercules release without the ESPSVM bug fix, usr this combination in your vm370ce.conf file:

ECPSVM YES
ECPVM DISABLE DISP1 DISP2

See the vm370ce.conf file for more details.

**Comment by RossPatterson** [comment]
It wasn't fixed in Hyperion 4.4.0.xxxx after all.  See https://github.com/SDL-Hercules-390/hyperion/issues/382 for details.  The fix will probably be in 4.8, but it isn't released yet.
