### ISSUE TITLE
tried snobol4 exec; no luck yet

### ISSUE THREAD

**Issue by rvjansen** [s390guy/vm370#92]
I copied test1 snobol4 u2 to my A drive. Tried to start the program:

```
snobol4 test1                                                                
NOTICE: THIS IS A NEW EXEC, AS OF 8/18/77. TYPE 'SNOBOL4 ?' FOR INSTRUCTIONS.
DMMSTA601S OPERAND 'SNOBOL4 ' NOT RECOGNIZED                                 
Ready; T=0.10/0.12 16:17:10                                                  
```

who can help?

**Comment by rvjansen** [comment]
There is one; it is just that I don't understand what the exec does, and why it has to announce that it is new; but I can't read exec.

**Comment by BobBolch** [comment]
I see some flaws in the SNOBOL4 EXEC. I have an appointment this morning, but I will check into this in a few hours.
Bob

**Comment by BobBolch** [comment]
Sorry this took so long. I have Covid, or something like it.
======
t snobol4 exec

*DATE: 08/18/77 TIME: 22:23:28 USER: G7089
*BEGTYPE ALL
*OTICE: THIS IS A NEW EXEC, AS OF 8/18/77. TYPE 'SNOBOL4 ?' FOR INSTRUCT
*END
&CONTROL ALL
&IF &$ EQ DEBUG &CONTROL ALL
&IF &INDEX EQ 0 &GOTO -HELP
&IF &1 EQ ? &GOTO -QUERY
&IF &1 EQ OPER &GOTO -OPER
STATE &1 SNOBOL4 *
&IF &RETCODE NE 0 &EXIT
FILEDEF 5 DISK &1 SNOBOL4 *
&XPRT = DISK
&XPUN = DISK
&R = 00010000
&L = 00035200
&H = 00200000
&IF &INDEX = 1 &GOTO -INVOKE
&COUNT = 2
-BACK &USE = &COUNT + 1
&GOTO -&&COUNT
-DISK &XPRT = DISK
&GOTO -PLUS1  -PRINT &XPRT = PRINT
MONITOR AUTO STARTING
&GOTO -PLUS1
-TERM &XPRT = TERM
&GOTO -PLUS1
-CDISK &XPUN = DISK
&GOTO -PLUS1
-CPUNCH &XPUN = PUNCH
&GOTO -PLUS1
-CTERM &XPUN = TERM
&GOTO -PLUS1
-R &X = &DATATYPE &&USE
&IF &X NE  NUM &GOTO -LP
&X = &LENGTH &&USE
&IF &X GE 6 &GOTO -LP
&Y = 8 - &X
&Z = &SUBSTR 00000000 1 &Y
&R = &CONCAT &Z &&USE
&GOTO -EPARM
-L &X = &DATATYPE &&USE
&IF &X NE NUM &GOTO -LP
&X = &LENGTH &&USE
&IF &X GE 6 &GOTO -LP
&Y = 8 - &X
&Z = &SUBSTR 00000000 1 &Y
&L = &CONCAT &Z &&USE
&GOTO -EPARM
-H &X = &DATATYPE &&USE
&IF &X NE NUM &GOTO -LP
&X = &LENGTH &&USE
&IF &X GE 7 &GOTO -LP
&Y = 8 - &X
&Z = &SUBSTR 00000000 1 &Y
&H = &CONCAT &Z &&USE
&GOTO -EPARM
-LP &TYPE &&USE IS INVALID FOR R/L/H
&EXIT 4
-EPARM &COUNT = &COUNT + 1
-DEBUG
-PLUS1 &COUNT = &COUNT + 1
-EPARM2 &IF &COUNT LE &INDEX &GOTO -BACK
&IF &XPRT NE DISK &GOTO -OTHPR
FILEDEF 6 DISK &1 LISTING
&SKIP 1
-OTHPR FILEDEF 6 &XPRT
&IF &XPUN NE DISK &GOTO -OTHPU
FILEDEF 7 DISK &1 CARDS
&SKIP 1
-OTHPU FILEDEF 7 &XPUN
-INVOKE GLOBAL TXTLIB FORTLIB
           SNOBOL4 &R &L &H

***** BEGIN GATHERING USE COUNTS *******
&RCODE = &RETCODE
&OFD = &DATE
&OFT = &TOD
STAT &OFD &OFT &ACCT &STORAGE SNOBOL4
***** END GATHERING USE COUNTS   *******
&EXIT
-HELP &BEGTYPE ALL
THIS EXEC IS USED TO EXECUTE SNOBOL PROGRAMS
ENTER 'SNOBOL4 ?' FOR MORE INFORMATION
&END
&EXIT
-QUERY &BEGTYPE ALL
A FILETYPE OF 'SNOBOL4' IS ASSUMED FOR THE PROGRAM TO BE EXECUTED. THE
PROGRAM MAY BE ON ANY DISK; THE DISKS WILL BE SEARCHED IN NORMAL
(ALPHABETICAL) ORDER. THIS EXEC INVOKES VERSION  3.5 OF
THE COMPILER, AS DESCRIBED IN THE PRENTICE-HALL BOOK 'THE SNOBOL4
PROGRAMMING LANGUAGE' (1971). DEFAULT MEMORY ALLOCATIONS OF R=10000,
L=35200, AND H=200000 ARE USED. THESE PARAMETERS ARE DESCRIBED IN THE
MWCC USER'S GUIDE. THE TIMING STATISTICS RETURNED BY SNOBOL4
UNDER CMS ARE NOT RELIABLE.
&END
-OPER &BEGTYPE ALL
ONE OPERAND IS REQUIRED: THE NAME OF THE FILE (CALLED FNAME, BELOW)
       CONTAINING THE SNOBOL4 PROGRAM TO BE EXECUTED.

THE FOLLOWING OPERANDS ARE OPTIONAL AND MAY BE SPECIFIED IN ANY ORDER:

DISK        KEEPS THE PRINTER OUTPUT (FILE 6) ON DISK IN FILE 'PROG
LISTING'
PRINT       PRINTS THE PRINTER OUTPUT

TERM        DIRECTS THE PRINTER OUTPUT TO THE TERMINAL

CDISK       KEEPS THE CARD OUTPUT (FILE 7) ON DISK IN FILE 'PROG CARDS'

CPUNCH      DIRECTS CARD OUTPUT TO THE PUNCH

CTERM       DIRECTS THE PUNCH OUTPUT TO THE TERMINAL

R           IS THE AMOUNT OF STORAGE RESERVED FOR OTHER USES.

L           IS THE LOW BOUND ON DYNAMIC STORAGE

H           IS THE HIGH BOUND ON DYNAMIC STORAGE





EXAMPLES: SNOBOL4 EPA    WILL RUN A SNOBOL PROGRAM IN FILE 'EPA SNOBOL4',

                         KEEPING PRINTER AND PUNCH OUTPUT IN DISK FILES

                         'EPA LISTING' AND 'EPA CARDS', RESPECTIVELY.



SNOBOL4 VALUE CPUNCH TERM H 300000     WILL EXECUTE A SNOBOL PROGRAM IN
FILE
                          'VALUE SNOBOL4', DIRECTING PRINTER OUTPUT TO THE

                          TERMINAL, AND PUNCH OUTPUT TO THE PUNCH.

                          THE COMPILER H VALUE WILL BE 300000 BYTES.

&END

&EXIT

**Comment by rvjansen** [comment]
This works very well, and executes the example programs flawlessly. It still fails on the 'stat' but I can change that myself. Now that it runs I will probably have a look at a rexx exec to see if I can make that work.

**Comment by rvjansen** [comment]
solved, closed.

**Comment by BobBolch** [comment]
If you have a REXX version, I would like to include it in VMCE.
Thanks/Bob

**Comment by rvjansen** [comment]
This is what I use:
```rexx
/*                                                                
 * REXX                                                           
 * EXECUTE A SNOBOL4 PROGRAM USING BELL'S LABS V3.5 COMPILER      
 */                                                               
 PARSE UPPER ARG FNAME REST                                       
 IF FNAME='' THEN DO                                              
   CALL USAGE                                                     
   EXIT                                                           
 END                                                              
 'STATE' FNAME 'SNOBOL4 *'                                        
 IF RC<>0 THEN EXIT                                               
 R = 00010000 ; L = 00035200 ; H= 00200000                        
 ADDRESS COMMAND                                                  
 IF WORDPOS('DISK',REST) > 0 THEN DO                              
   'FILEDEF 6 DISK' FNAME 'LISTING *'                             
 END                                                              
 ELSE DO                                                          
   'FILEDEF 6 TERMINAL'                                           
 END                                                              
 'FILEDEF 5 DISK' FNAME 'SNOBOL4 *'                               
 'SNOBOL4' R L H                                                  
EXIT                                                              
 USAGE:                                                           
 say 'The SNOBOL4 EXEC runs a SNOBOL4 program'                    
 say 'Using Bell Telephone Laboratories, Inc. Macro Compiler'     
 say '(Version 3.5, Feb. 10, 1971)'                               
 say 'Usage:'                                                     
 say 'SNOBOL4 progname [disk|term]'                               
 say 'A file type of SNOBOL4 (RECFM F) is assumed.'               
```

I can write a help text for it if you like.

**Comment by marXtevens** [comment]
After some digging, I found that STAT is part of IPCS, due to the DMM error prefix. I would recommend deleting that line from the EXEC/REXX code, as we don't have the IPCS Virtual Machine defined in USER DIRECT, nor have I been able to find a copy of the IPCS User Guide, nor Reference Manual.
