### ISSUE TITLE
BREXX DO loop counting weirdness

### ISSUE THREAD

**Issue by RossPatterson** [s390guy/vm370#96]
[boom11.zip](https://github.com/s390guy/vm370/files/14624184/boom11.zip)
I've seen this randomly a couple of times, but today I built a repeatable test case.  Using a simple Rexx iterative loop, BREXX occasionally goes quite literally crazy, generating either floating point numbers for the loop index, or randomly resetting the index to 0.

I thinned down the Rexx program I was running until it couldn't get any plainer.  The below files BOOM11 EXEC and CONSOLE demonstrate both behaviours.  `BOOM11 EXEC` reads a `TEXT` deck file via` EXECIO DISKR * (STEM`, and then simply loops over it, with tracing active, writing the loop index to the console. At line 144 in `BOOM11 CONSOLE`, you can see it resetting from 7 to 0, and later at 248, the "8" is shown as "8E+20".

GitHub doesn't allow uploading `VMARC` files, so download `boom11.zip` and rename it to `boom11.vmarc`, then upload it in binary to your CMS system.

(see also the h390-vm thread at https://groups.io/g/h390-vm/topic/brexx_do_loop_counting/104958037)

**Comment by rvjansen** [comment]
I'm sorry, but also with the provided exec and input, I cannot reproduce here. Everything seems fine, and I do not see the symptoms - it counts to 170 without a hitch. You don't have a older brexx or c runtime in the search path?

**Comment by RossPatterson** [comment]
> You don't have a older brexx or c runtime in the search path?

Nope, this is a brand new userid on a brand new Hercules and VM/370 CE 1.2 system.  Everything on it, except for a few Rexx EXECs I've written and DISASM MODULE from NOTE DISAM on VMSHARE, is exactly as shipped.

**Comment by RossPatterson** [comment]
I've managed to thin this down to the smallest possible test case, and eliminate everything but BREXX.  Some folks have asked about other things that might cause the failure, so I did the followng:

1. Created a `TEST EXEC` that just does this:
```Rexx
/* */
Do I = 1 to 170
    Say I
End

Exit 0
```
2. Created a `TESTDOC EXEC` that shows the userid, the disks attached and ACCESSed, the `BREXX TEXT` file location, the size of the machine, the BREXX version, and the contents of the `TEST EXEC`.
3. Created a `TEST` userid with a T-DISK 191, sent the two files to it, and ran them.

As the attached console file `test_console.txt` shows, on the 4th execution of `TEST EXEC` (starting at line 565), the loop counter `I` displayed "2" as "2E+13" (line 567), and displayed 0 instead of 4 (line 569) and 21 (line 586).

This is a new userid with no writable permanent disks, the S-disk and Y-disk are exactly as shipped in VM/370 CE 1.2, I'm running Hercules Hyperion version 4.6.0.10941-SDL-g65c97fd6, and I've never had any other version of Hercules or VM/370 on this machine.  This is as close as possible to a virgin system as I can get.

When I said "weird", I meant it :-)

**Comment by RossPatterson** [comment]
Hey @BobBolch - Any chance what I'm seeing is part and parcel of the GCC saved segment thing you mentioned in #83?

**Comment by RossPatterson** [comment]
There are definitely two bugs.  The floating-point-display problem is an output issue, and has nothing to do with the reset-to-zero problem.   I'm going to split the reset-to-zero off to a new issue.

**Comment by RossPatterson** [comment]
The floating-point-display issue is a bug in BREXX's `Lformat()` routine in `FORMAT C` .  I narrowed it down by building a `DEBUG` version of BREXX, and changing `INTERPRE C` to call its `DebugStackList()` routine at the top of the interpretation loop in `RxInterpret()`, right before executing the next i-code instruction.  The console shows very clearly the failure:

```Rexx
.104.NEWCLAUSE
    #0: "170"
.108.NEWCLAUSE
    #0: "170"
.112.LOAD."I"
    #1: "1"
    #0: "170"
.124.SAY."1"
1
    #0: "1.7E+15"
.128.LOAD."I"
    #1: "1"
    #0: "170"
```

The `"1.7E+15"` in the stack dump before the `LOAD` instruction at offset 128 is printed by exactly the same routine as the `"170"` following it, and from exactly the same location in memory, called in both cases by `DebugStackList()`.  The printing is done by `Lprint()` in `PRINT C`, which pushes almost all the work off to `Lformat()`.  For some reason that I have not yet determined, `Lformat()` sometimes formats the fullword value 0x000000AA as "170" and sometimes as "1.7E+15".  There's a lot of floating-point to character conversion code in it, and I don't (yet?) understand most of it.  I also don't (yet?) understand why it doesn't use the C Standard Library's conversion function.

The code in `DebugStackList()` simply says `Lprint(STDOUT,(context->interpre_RxStck)[i]);', and I did not modify it.

I'll be offline for a week or two, but I'll get back to looking at this when I return.

**Comment by rvjansen** [comment]
Bob,

I seem to remember that I am on a preview of 1.3CE which announces itself as 1.2 - would there be any chance that is the reason I cannot reproduce this issue?

**Comment by BobBolch** [comment]
Hi Rene,
The only fix in 1.3 that looks at all related to me is:
Errors with more than 7 arguments given to REXX EXECs, bREXX does not even
start #83

Issue #83 includes the procedure to resave the segment correctly. I sent
Ross this info,
but he never said that he tried it. I have had doctor visits every day this
week, but I will try that
today. (Also, I could not produce his symptoms on 1.2).

Bob

**Comment by RossPatterson** [comment]
On Thu, Mar 21, 2024 at 08:34 Bob Bolch ***@***.***> wrote:

> Issue #83 includes the procedure to resave the segment correctly. I sent
> Ross this info,
> but he never said that he tried it.


Since that point, I've been running my tests in a 16M VM, so GCCLIB is
being loaded into memory, bypassing the segment issue.  (I didn't want to
change the underlying system irreversibly by resaving the segment.)

I updated issue 96 last night - the floating point issue is absolutely a
BREXX bug.  I can reproduce it in a debug build running nothing but Rexx
code, and the console shows the binary int value being on the stack and
being incorrectly displayed as a float (but only sometimes).

I  believe the reset to 0 problem is independent, and I'll pursue it when
the float issue is resolved.

I'm going to be offline for a week or so, but I'll get back on this when I
return.

Ross

**Comment by RossPatterson** [comment]
I'm back online, and digging deeper into this.  For reasons that I don't yet understand, the `round_sig_digits()` code in `FORMAT C` that determines the significand for a number to be formated (below) swings the exponent +/-14, seemingly randomly.

```c
double factor = pow(10.0, digits - ceil(log10(fabs(value))));
```

For example, my debugging code logged this in the most recent test case:

```
FORMAT: rsd: 9 - ceil(log10(fabs(170.000000))) = -7.000000!
```

`fabs(170.0)` is, of course, 170,0, and `log10(170.0)` should be 2.23045, give or take rounding.  So `ceil(2.2...)` should be 3.0, but 9 - 3.0 is not -7.0, except that this code says so sometimes.

I'm continuing to explore the source of this issue.

**Comment by RossPatterson** [comment]
I wrapped the functions in that expression, and dumped their inputs and outputs to the console.  It took several attempts, but I caught this error:

```
FORMAT: rsd: fabs(170.000000) = 170.000000
FORMAT: rsd: log10(170.000000) = 15.437074 <<< ERROR!
FORMAT: rsd: ceil(15.437074) = 16.000000
FORMAT: rsd: pow(10.000000, -7.000000) = 0.00000009
FORMAT: rsd: 9 - ceil(log10(fabs(170.000000))) = -7.000000
```

The base-10 logarithm of 170 is about 2.23045, but the GCCLIB `log10()` function sometimes returns 15.437074.   The code in GCCLIB's `MATH C` is simple:

```c
static const double ln10 = 2.3025850929940456840179914546844;
...
double log10(double x) {
    return (log(x) / ln10);
}
```

The natural logarithm code, `log()`, is more complex, but it must be where the problem starts.  Time to keep digging deeper.

**Comment by Fish-Git** [comment]
> The base-10 logarithm of 170 is about 2.23045, but the GCCLIB `log10()` function sometimes returns 15.437074.

Maybe Paul is using a buggy version of GCCLIB? Just for fun, I did some googling for "gcc log10 bug" and it looks like at least some of the resulting hits hints at a possible bug in gcc's log10 and/or log function?

I also saw something about incorrect results when the &lt;match.h&gt; header isn't #included beforehand, as well as one about uncaught floating point exceptions or rounding modes.

Dealing with floating point in programs is not for the faint of heart. There are many "Gotcha!"s.

**Comment by RossPatterson** [comment]
I've just closed Issue #98 as a duplicate of this one.  Contrary to what I said above on 2024-03-20, the reset-to-zero issue boils down to the same problem I've been chasing above.  Everything is coming down to the GCCLIB natural logarithm function `log()` occasionally, and unpredictably, returning ridiculous values (_e.g._,  `log(170.000000)` came out as 35.545177, but the correct value is roughly 5.135798).

**Comment by RossPatterson** [comment]
As I just said over at https://github.com/SDL-Hercules-390/hyperion/issues/382, I think I understand what's happening here.  If I'm correct, the fix for that Hercules issue means that VM applications running under Hyperion that expect floating point register 4 to have a stable value over a bunch of instructions may find that it is occasionally, and unpredictably, damaged.  That almost exactly describes the `log()` function in GCCLIB's `math.c`, which computes the natural logarithm via a Taylor series, using FPR4 as the accumulator.  In my tests, it is common to go over 30 passes through the loop before the accumulator reaches its final value.

BRexx makes _a lot_ of use of the `log()` function - way more than you might expect.

**Comment by RossPatterson** [comment]
At this point, I'm convinced.  I have built and tested two versions of Hercules Hyperion that do not demonstrate the failure.  The first, a build of the [`sharedvfp` branch](https://github.com/SDL-Hercules-390/hyperion/tree/sharedvfp) has work in progress that reorganizes how the floating point registers and managed.  The second is a build of the master branch with a patch of my own.

# WORKAROUND:

Until and unless you get a modified Hercules build, disable the `DISP1` and `DISP2` ECPS:VM assists, by adding this line to your Hercules configuration file (_e.g._, `VM370CE.V1.R1.2\vm370ce.conf`):

```
ecpsvm disable disp1 disp2
```
